URL = https://raw.githubusercontent.com/acobaugh/tf-build-harness/master/tf-build-harness.mk
-include $(shell test -f .tf-build-harness.mk || curl -sSL -o .tf-build-harness.mk "$(URL)"; echo .tf-build-harness.mk)
